// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Chirichella Inc.
// "Licences and source" opens in place. The editor runs in a sandboxed frame
// with no popups and no top navigation, so a link to licenses.html could only
// replace the frame itself: before ev.ready that ends the host's boot, after
// it a live editor (and Back reloads an island whose hello the host ignores).
// So the control is a button that opens an overlay above the loading screen
// and above the editor (role dialog, aria-modal, a Close button, Escape
// closes, focus moved in and given back). The overlay fetches the release's
// own licenses.html (connect-src 'self') and renders its body through
// DOMParser, with scripts, styles and handlers stripped; its links to the
// files beside it (LICENSE.txt, NOTICE.txt) open in the same overlay. Nothing
// navigates.

export const LICENCES_COPY = {
  title: 'Licences and source',
  close: 'Close',
  back: 'Back to the licences',
  loading: 'Opening the licences',
  failed: 'The licences could not be opened here. They are served beside the editor as licenses.html.',
} as const;

/** The page the overlay opens first: generated by scripts/notices.mjs beside index.html. */
export const LICENCES_PAGE = 'licenses.html';

/**
 * A link the overlay may follow: a bare file name beside the licences page
 * (no scheme, no folder, no query), an .html or a .txt. Anything else is not
 * followed (and its href is dropped when the page is rendered).
 */
export function docName(href: string | null | undefined): string | null {
  if (href == null) return null;
  return /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.(?:html|txt)$/.test(href) && !href.includes('..') ? href : null;
}

export type DocKind = 'html' | 'text';
export const docKind = (name: string): DocKind => (name.endsWith('.html') ? 'html' : 'text');

export type LicencesState =
  | { kind: 'loading'; name: string }
  | { kind: 'doc'; name: string; doc: DocKind; body: string }
  | { kind: 'failed'; name: string };

/** What the controller drives; the DOM implementation is mountLicences below. */
export interface LicencesView {
  /** Mount the dialog and move focus into it. */
  show(): void;
  /** Unmount the dialog and give focus back to where it was. */
  hide(): void;
  render(state: LicencesState): void;
}

export interface LicencesController {
  isOpen(): boolean;
  /** Opens the overlay (once) and shows the named document, the licences page by default. */
  open(name?: string): void;
  close(): void;
  /** A key pressed while the overlay may be open: Escape closes it. Answers whether the key was taken. */
  key(key: string): boolean;
}

/** The open and close logic, DOM-free: `load` answers a document's text or throws. */
export function createLicencesController(view: LicencesView, load: (name: string) => Promise<string>): LicencesController {
  let open = false;
  let seq = 0;
  const close = (): void => {
    if (!open) return;
    open = false;
    seq += 1;   // a load still in flight renders nothing
    view.hide();
  };
  return {
    isOpen: () => open,
    open(requested = LICENCES_PAGE) {
      const name = docName(requested);
      if (name == null) return;
      if (!open) {
        open = true;
        view.show();
      }
      const mine = ++seq;
      view.render({ kind: 'loading', name });
      load(name).then(
        (body) => { if (open && mine === seq) view.render({ kind: 'doc', name, doc: docKind(name), body }); },
        () => { if (open && mine === seq) view.render({ kind: 'failed', name }); },
      );
    },
    close,
    key(key) {
      if (!open || key !== 'Escape') return false;
      close();
      return true;
    },
  };
}

// ---------------------------------------------------------------- the DOM side

/** Elements never carried over from the fetched page. */
const STRIP = 'script, style, link, meta, base, iframe, frame, object, embed, form, input, button, textarea, select, img, svg, math, template';

/** The fetched page's body as nodes of this document: no script, no style, no handler, no id, local links only. */
export function renderHtmlBody(text: string, doc: Document = document): DocumentFragment {
  const parsed = new DOMParser().parseFromString(text, 'text/html');
  for (const el of Array.from(parsed.body.querySelectorAll(STRIP))) el.remove();
  for (const el of Array.from(parsed.body.querySelectorAll('*'))) {
    for (const attr of Array.from(el.attributes)) {
      const n = attr.name.toLowerCase();
      if (n.startsWith('on') || n === 'id' || n === 'style' || n === 'srcset' || n === 'src' || n === 'action' || n === 'formaction') el.removeAttribute(attr.name);
    }
    if (el.tagName === 'A') {
      // Every attribute of a link goes but its class; a local link gets its name back.
      const name = docName(el.getAttribute('href'));
      for (const attr of Array.from(el.attributes)) if (attr.name !== 'class') el.removeAttribute(attr.name);
      if (name != null) {
        el.setAttribute('href', name);
        el.setAttribute('data-doc', name);
      }
    }
  }
  const frag = doc.createDocumentFragment();
  for (const node of Array.from(parsed.body.childNodes)) frag.append(doc.importNode(node, true));
  return frag;
}

const FOCUSABLE = 'button:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])';

let controller: LicencesController | null = null;

function el<K extends keyof HTMLElementTagNameMap>(tag: K, className: string, text?: string): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  node.className = className;
  if (text != null) node.textContent = text;
  return node;
}

/** Builds the overlay on first use; one per page, mounted on body above #screen and the editor. */
function mountLicences(): LicencesController {
  if (controller != null) return controller;
  let overlay: HTMLElement | null = null;
  let content: HTMLElement | null = null;
  let back: HTMLButtonElement | null = null;
  let closeButton: HTMLButtonElement | null = null;
  let returnFocus: HTMLElement | null = null;

  const view: LicencesView = {
    show() {
      returnFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
      overlay = el('div', 'cc-licences-overlay');
      overlay.id = 'cc-licences';
      overlay.setAttribute('role', 'dialog');
      overlay.setAttribute('aria-modal', 'true');
      overlay.setAttribute('aria-labelledby', 'cc-licences-title');
      const bar = el('div', 'cc-licences-bar');
      const title = el('h2', 'cc-licences-title', LICENCES_COPY.title);
      title.id = 'cc-licences-title';
      back = el('button', 'cc-licences-action', LICENCES_COPY.back);
      back.type = 'button';
      back.hidden = true;
      back.addEventListener('click', () => controller?.open(LICENCES_PAGE));
      closeButton = el('button', 'cc-licences-action', LICENCES_COPY.close);
      closeButton.type = 'button';
      closeButton.addEventListener('click', () => controller?.close());
      bar.append(title, back, closeButton);
      content = el('div', 'cc-licences-doc');
      content.tabIndex = -1;
      content.addEventListener('click', (e) => {
        const a = e.target instanceof Element ? e.target.closest('a') : null;
        if (a == null) return;
        e.preventDefault();   // nothing in the overlay navigates the frame
        const name = a.getAttribute('data-doc');
        if (name != null) controller?.open(name);
      });
      overlay.append(bar, content);
      document.body.append(overlay);
      closeButton.focus();
    },
    hide() {
      overlay?.remove();
      overlay = null;
      content = null;
      back = null;
      closeButton = null;
      if (returnFocus != null && returnFocus.isConnected) returnFocus.focus();
      returnFocus = null;
    },
    render(state) {
      if (content == null) return;
      if (back != null) back.hidden = state.name === LICENCES_PAGE;
      content.setAttribute('aria-busy', state.kind === 'loading' ? 'true' : 'false');
      if (state.kind === 'loading') {
        content.replaceChildren(el('p', 'cc-licences-note', LICENCES_COPY.loading));
      } else if (state.kind === 'failed') {
        content.replaceChildren(el('p', 'cc-licences-note', LICENCES_COPY.failed));
      } else if (state.doc === 'html') {
        content.replaceChildren(renderHtmlBody(state.body));
      } else {
        content.replaceChildren(el('pre', 'cc-licences-text', state.body));
      }
      content.scrollTop = 0;
    },
  };

  controller = createLicencesController(view, async (name) => {
    const res = await fetch(`${import.meta.env.BASE_URL}${name}`, { credentials: 'same-origin', cache: 'no-cache' });
    if (!res.ok) throw new Error(`${res.status}`);
    return res.text();
  });

  // Installed with the first screen, before the engine's scripts load, so this
  // capture listener runs ahead of the engine's own keyboard handling.
  window.addEventListener('keydown', (e) => {
    if (controller == null || !controller.isOpen() || overlay == null) return;
    if (controller.key(e.key)) {
      e.preventDefault();
      e.stopImmediatePropagation();
      return;
    }
    if (e.key === 'Tab') {
      // Focus stays inside the dialog while it is open.
      const items = Array.from(overlay.querySelectorAll<HTMLElement>(FOCUSABLE)).filter((n) => !n.hidden);
      if (items.length > 0) {
        const first = items[0];
        const last = items[items.length - 1];
        const inside = document.activeElement instanceof Node && overlay.contains(document.activeElement);
        if (!inside || (e.shiftKey && document.activeElement === first)) { e.preventDefault(); (e.shiftKey ? last : first).focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    }
    // Keys typed in the dialog are the dialog's, not the editor's.
    if (e.target instanceof Node && overlay.contains(e.target)) e.stopImmediatePropagation();
  }, true);

  return controller;
}

/** The "Licences and source" control every island screen carries. */
export function licencesButton(): HTMLButtonElement {
  const button = el('button', 'cc-licences', LICENCES_COPY.title);
  button.type = 'button';
  button.setAttribute('aria-haspopup', 'dialog');
  const c = mountLicences();
  button.addEventListener('click', () => c.open(LICENCES_PAGE));
  return button;
}
